import Foundation

/// Bundled glance payloads, one per recorded incident, generated by
/// dashboard/scripts/make-glance-fixtures.mjs from the daemon's own scenarios.
/// Used by fixture mode (screenshots, demos, working without a fleet) and by
/// the tests.
public enum Fixtures {
    public static let names = [
        "live", "quiet", "waiting", "dead", "diskHold", "diskBelowIdle",
        "saturated", "accountBlocked", "drift", "agentDown", "blind",
    ]

    public static func data(_ name: String) throws -> Data {
        guard let url = Bundle.module.url(forResource: name, withExtension: "json", subdirectory: "Fixtures") else {
            throw CocoaError(.fileNoSuchFile, userInfo: [NSFilePathErrorKey: "Fixtures/\(name).json"])
        }
        return try Data(contentsOf: url)
    }

    public static func glance(_ name: String) throws -> Glance {
        try Glance.decode(data(name))
    }
}
